### PR TITLE
Update version to v0.3.11, Fix INTERFACE64, gcc version

### PR DESCRIPTION
**Pull request by mattip**
Fixes gh-42. There must be a better way to get the matrix values into the environment, but this should work.

### CODE REVIEW

**Comment by mattip** [comment]
Merging this will change the hashes for the already-uploaded packages. Should I go ahead and get the HEAD from OpenBLAS so we can check their fix for numpy/numpy#16774 ?

**Comment by mattip** [comment]
... and of course I have a typo.

**Comment by mattip** [comment]
gcc fails to compile 0.3.11 since the mingw version is 8.1.0 which suffers from [this bug](https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=dd341e6b9a8254a6b41b146afce0917889f5bb6a): 
```
config/i386/avx512fintrin.h (_mm512_abs_pd, _mm512_mask_abs_pd): Use
__m512d type for __A argument rather than __m512
```

It doesn't appear that there are later versions of mingw available.

**Comment by mattip** [comment]
[skip travis]

**Comment by mattip** [comment]
Now getting
```
undefined reference to `dgetri_`
```
in 32-bit tests. When do we drop windows 32-bits?

**Comment by tylerjereddy** [comment]
> When do we drop windows 32-bits?

My impression was that Python 32-bit interpreter installs on Windows were still very common for whatever reason. I think Matthew Brett may have been saying that?

**Comment by charris** [comment]
> I think Matthew Brett may have been saying that?

That's also my recollection.

**Comment by mattip** [comment]
I was blaming the 32-bit build too soon. I set `fail-fast` to false so all builds run to completion, and they all give the `undefined reference to dgetri_` error. I am trying to reproduce locally.

**Comment by matthew-brett** [comment]
About importance of Windows 32-bit bit - yes, that is usually me quoting Steve Dower : https://github.com/pypa/manylinux/issues/118#issuecomment-481404761 . I haven't investigated the wheel download statistics though.

**Comment by mattip** [comment]
something is still off with the interface64 builds, the internal OpenBLAS linktest is failing.

**Comment by mattip** [comment]
self-merging to move this chain of fixes forward

**Pull request merged**
