### PR TITLE
Manylinux 2 24

### PR DESCRIPTION
**Pull request by mattip**
Add a manylinux_2_24 build and update multibuild

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Not sure if it helps, but looks like CI may be choking because of this and similar `multibuild` lines: https://github.com/matthew-brett/multibuild/blob/devel/common_utils.sh#L343

I checked the same docker image locally and `python3` works with that command, but not `python` itself.

**Comment by mattip** [comment]
> I checked the same docker image locally and python3 works with that command, but not python itself.

Thanks. The image is based on Debian not CentOS, and they do not install python by default. I will make a PR to multibuild.

**Comment by mattip** [comment]
It seems we need support for gcc7+ to build OpenBLAS, manylinux_2_24 comes with gcc 6.3.10. I will try to update the manylinux image.

**Comment by mattip** [comment]
ahh, [not so simple](https://github.com/pypa/manylinux/issues/1012#issuecomment-787030543). Updating gcc on debian will also update libgcc++. :(

**Comment by matthew-brett** [comment]
Is it practical to compile gcc?

**Comment by mattip** [comment]
I guess that is what needs to be done, in a way that preserves the system libraries so they will be "portable" to standard debian9 machines.

**Comment by mattip** [comment]
Closing as abandoned.

**Pull request closed without merging**
