### PR TITLE
update to pre-0.3.9 commit

### PR DESCRIPTION
**Pull request by mattip**
In a short discussion with the OpenBLAS devs, they recommend this commit, at least until 0.3.9 is released.

xref xianyi/OpenBLAS#2445

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Right, I have an issue open indicating that `0.3.9` will be preferable for `0.3.8` given all the issues discovered upstream.

**Comment by tylerjereddy** [comment]
I don't usually bump the submodule; I can't remember why we have that here, the `BUILD_COMMIT` should probably suffice.

**Comment by mattip** [comment]
Thanks, missed appveyor

**Comment by mattip** [comment]
I hope this or the previous one will clear the segfault in MacPython/numpy-wheels#73

**Comment by tylerjereddy** [comment]
I restarted the one failing s390x job. Did you push the appveyor change, I don't see it

**Comment by mattip** [comment]
Updated the appveyor and removed the submodule update. CI is green.

**Comment by tylerjereddy** [comment]
Nice! Merging, thanks Matti,

Will be interesting to see if the anaconda.org handling of assets for two versions of OpenBLAS looks "ok."

**Pull request merged**
