### PR TITLE
try commit 349b722d8d09303

### PR DESCRIPTION
**Pull request by mattip**
Build openblas libraries for 349b722d8d09303 to maybe fix numpy/numpy#16913

### CODE REVIEW

**Comment by bashtage** [comment]
You might need to make -j 2 on appveyor to avoid time out.  I think each AppVeyor instance has 2 real CPUs.

**Comment by mattip** [comment]
Appveyor succeeded, macOS on travis failed. It seem it miscompiled somehow: did not properly generate config_kernel.h. Is there a way to restart just that travis run?

**Comment by bashtage** [comment]
If you are an owner you can log into Travis and you should see a restart icon on the job.

image

**Comment by bashtage** [comment]
Somehow I am an owner, so I restarted it.

**Comment by mattip** [comment]
build succeeded. I will self-merge to move this forward. It should not delete the current artifacts at https://anaconda.org/multibuild-wheels-staging/openblas-libs/files, only add to them. Then the next step is to make a PR to numpy/numpy to update tools/openblas_support.py, updating OPENBLAS_V to the string inside the DLL and OPENBLAS_LONG to the name of the download file. In order to avoid the problem of updating all the hashes, the check for `if sha256_returned != sha256_expected` can be disabled. Much of this all can be tested with `python tools/openblas_support.py --test`

**Pull request merged**
