### PR TITLE
pick up PR 2527 from OpenBLAS

### PR DESCRIPTION
**Pull request by mattip**
xref numpy/numpy#15796, which led to xianyi/OpenBLAS#2526, which led to xianyi/OpenBLAS#2527.

### CODE REVIEW

**Comment by mattip** [comment]
close-reopen to try to trigger travis

**Comment by mattip** [comment]
@tylerjereddy any idea why travis isn't running?

**Comment by tylerjereddy** [comment]
It could happen if there's a yaml syntax error, but your change is so simple I can't imagine that's the case.

I think Chuck recently had to bump the Linux distro used by Travis to get triggers working for numpy-wheels branch (?), but that may also be a stretch..

**Comment by mattip** [comment]
I cleaned up the warnings and it started. Who knows?

**Comment by tylerjereddy** [comment]
Failures do look OpenBLAS-related

**Comment by tylerjereddy** [comment]
Oy, typo in the `git` hash or is there some craziness in upstream machinery somewhere?

**Comment by mattip** [comment]
I am trying out a newer version of the patch, as requested in [this comment](https://github.com/xianyi/OpenBLAS/pull/2533#issuecomment-605433039) It is not yet merged to the main repo, so I need to get it from the patch originator's repo.

**Comment by mattip** [comment]
The s390x build is failing. It seems only merged PRs upload to the staging area. Could we merge this then revert the merge so I can try out the artifacts on the PyPy CI run in NumPy? Is there another way to get the artifact out of the build and over to the NumPy build?

**Comment by tylerjereddy** [comment]
> Is there another way to get the artifact out of the build and over to the NumPy build?

For Appveyor there's an artifacts tab you can click; don't think Travis has that.

> Could we merge this then revert the merge so I can try out the artifacts on the PyPy CI run in NumPy?

You should be able to just push your feature branch to this repo and if you open a PR from that branch it should get staged I think. The secret keys aren't available if you open the PR from your fork. At least, that is how it used to work. Otherwise, probably best to just wait for OpenBLAS master to get whatever fix is needed.

**Pull request closed without merging**
