### PR TITLE
update to latest develop, add TARGETs

### PR DESCRIPTION
**Pull request by mattip**
add minimal build targets for the various platforms

### CODE REVIEW

**Comment by mattip** [comment]
@isuruf what should the TARGET be on s390x, ppc64le? I used PRESCOTT for x86_32 and x86_64, and ARMV8 on aarch64.

**Comment by isuruf** [comment]
For ppc64le, `POWER8`.
For s390x `ZARCH_GENERIC` or `Z13` or `Z14`. Not sure which one is appropriate.
For `x86`, I think `KATMAI`, but not sure.

**Comment by tylerjereddy** [comment]
Note that artifacts from this PR may be uploaded as you iterate here since the feature branch is on the repo itself.

**Comment by mattip** [comment]
closing, will re-submit via a fork

**Pull request closed without merging**
