### PR TITLE
update multibuild to latest devel

### PR DESCRIPTION
**Pull request by mattip**

### CODE REVIEW

**Comment by mattip** [comment]
Not clear why this conflicts. I did
```
git checkout -f master
git submodule update
git checkout -b update-multibuild
cd multibuild
git checkout devel
cd ..
git commit -am"update multibuild to latest devel"
```

Why should that cause a merge conflict?

**Comment by matthew-brett** [comment]
I don't get a merge conflict with:

```
git co master
git submodule update --init
cd multibuild
git co devel
cd ..
git add multibuild
git commit -m "Update to latest multibuild"
```

What merge conflict do you get?

**Comment by mattip** [comment]
In this PR there is a merge conflict

**Comment by mattip** [comment]
The diff in this pr is
```
$ git diff
diff --git a/multibuild b/multibuild
index 7684e52..2bf2b36 160000
--- a/multibuild
+++ b/multibuild
@@ -1 +1 @@
-Subproject commit 7684e52bcb023d511c4f17b638d497203f218a68
+Subproject commit 2bf2b360f084aaa4b166935c3bd279e2e842f6ff

```

I could force push, but I would like to know what is wrong

**Comment by matthew-brett** [comment]
Hmm - when I do a checkout of the master branch, I get a multibuild commit of `04e209bc00b34f5c5d88d06fd547ab3eaf990a87` .

Can you replicate the merge conflict locally?

**Comment by mattip** [comment]
Thanks, I had to update my local `master` and rebase the PR off it. That cleared the conflict.

**Comment by mattip** [comment]
No need to wait for windows builds

**Pull request merged**
